#!/bin/bash

# composer require friendsofphp/php-cs-fixer
echo ":: Run Php-Cs-Fixer Analyse"
docker/symfony/cmd  vendor/bin/php-cs-fixer fix ./src --dry-run  --allow-risky=yes --diff --rules=@Symfony,@PSR12   
docker/symfony/cmd  vendor/bin/php-cs-fixer fix ./tests --dry-run  --allow-risky=yes --diff --rules=@Symfony,@PSR12 