version: '3.4'

services:
  php:
    container_name: PHP_P_AE
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    networks:
      - P_AE_network


networks:
  P_AE_network:
   driver: bridge