version: '3.4'

services:
  php:
    container_name: PHP_P_NF
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 8002:8000
      - 9003:9003 
    volumes:
      - ./:/var/www/html
      - ./var/xdebug/xdebug:/logs/xdebug
      - ./logs/php-fpm/:/tmp/xdebug_log
      - ./docker/php/xdebug.ini.dev:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    networks:
      - P_NF_network
      - background_network
  
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - P_NF_network
 
  postgres:
    image: postgres:13.4-alpine
    container_name: DB_Postgres_P_NF
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=NF
    ports:
      - 5433:5432
      - 29002:29001
    volumes:
      - P_NF_volume:/var/lib/mysql
    networks:
      - P_NF_network


volumes:
  P_NF_volume:

networks:
  P_NF_network:
   driver: bridge
  background_network:
      name: background_network
      driver: bridge
      external: true