openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:8002
paths:
  /notification:
    post:
      summary: Snd notfication
      parameters:
        - in: header
          name: Authorization 
          schema:
            type: string
            example: 1234567890
          required: true
      security:
        - bearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:     
              type: object
              properties:
                type:
                  type: string
                email:
                  type: string
                context:
                  type: string
                subject:
                  type: string
               
              example:  
                type:  "email"
                email: "my123.nowy.email@test"
                context: "Hi. You accont was created. :) Welcome :)"
                subject: User was creeated"
      responses:
        '200':
          description: OK
        '400':
            description: Bad Request

components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer