#!/bin/bash

# composer require friendsofphp/php-cs-fixer
echo ":: Run Php-Cs-Fixer Fix "
docker/cmd  vendor/bin/php-cs-fixer fix ./src   --allow-risky=yes --diff --rules=@Symfony,@PSR12   
docker/cmd  vendor/bin/php-cs-fixer fix ./tests  --allow-risky=yes --diff --rules=@Symfony,@PSR12 