var classes = [
    {
        "name": "App\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Command\\CreateEmailNotifcationCommand",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Application\\Write\\Command\\CommandInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Application\\Write\\Command\\CommandInterface"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 73.97,
        "mIwoC": 73.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\NF\\Application\\Write\\Command\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Command\\SendEmailCommand",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Application\\Write\\Command\\CommandInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Application\\Write\\Command\\CommandInterface"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 73.97,
        "mIwoC": 73.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\NF\\Application\\Write\\Command\\",
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Command\\TypeNotificationCommand",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 116.56,
        "mIwoC": 84.62,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\NF\\Application\\Write\\Command\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Handler\\CreateNotificationEventHandler",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Messenger\\Handler\\MessageHandlerInterface",
            "App\\NF\\Domain\\Repository\\NotificationRepositoryInterface",
            "Symfony\\Component\\Messenger\\MessageBusInterface",
            "App\\NF\\Application\\Write\\Command\\CreateEmailNotifcationCommand",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Model\\EmailDetailsNotification",
            "App\\NF\\Domain\\Model\\Notification",
            "App\\NF\\Application\\Write\\Command\\SendEmailCommand",
            "Symfony\\Component\\Messenger\\Envelope",
            "Symfony\\Component\\Messenger\\Stamp\\DispatchAfterCurrentBusStamp"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\Messenger\\Handler\\MessageHandlerInterface"
        ],
        "lcom": 2,
        "length": 20,
        "vocabulary": 8,
        "volume": 60,
        "difficulty": 1.29,
        "effort": 77.14,
        "level": 0.78,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 46.67,
        "number_operators": 2,
        "number_operands": 18,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 62.41,
        "mIwoC": 62.41,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 36.21,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.43,
        "totalSystemComplexity": 72.43,
        "package": "App\\NF\\Application\\Write\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Handler\\NotSuccessfullySentNotificationExceeption",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\NF\\Application\\Write\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\NF\\Application\\Write\\Handler\\SendEmailHandler",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Messenger\\Handler\\MessageHandlerInterface",
            "Symfony\\Component\\Mailer\\MailerInterface",
            "App\\NF\\Application\\Write\\Command\\SendEmailCommand",
            "DateTimeImmutable",
            "Symfony\\Component\\Mime\\Email",
            "App\\NF\\Application\\Write\\Handler\\NotSuccessfullySentNotificationExceeption"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\Messenger\\Handler\\MessageHandlerInterface"
        ],
        "lcom": 2,
        "length": 24,
        "vocabulary": 15,
        "volume": 93.77,
        "difficulty": 3.09,
        "effort": 289.82,
        "level": 0.32,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 30.34,
        "number_operators": 7,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 58.95,
        "mIwoC": 58.95,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "package": "App\\NF\\Application\\Write\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Event\\CreatedNotificationEvent",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateCalled",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDetailsNotification",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDetails",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface",
            "DateTimeImmutable",
            "ReflectionClass",
            "DateTimeImmutable",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface"
        ],
        "lcom": 1,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 2.2,
        "effort": 260.27,
        "level": 0.45,
        "bugs": 0.04,
        "time": 14,
        "intelligentContent": 53.77,
        "number_operators": 11,
        "number_operands": 22,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 43,
        "lloc": 43,
        "mi": 49.72,
        "mIwoC": 49.72,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.63,
        "relativeSystemComplexity": 6.63,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 21,
        "totalSystemComplexity": 53,
        "package": "App\\NF\\Domain\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Event\\EventLogs\\EventLogsTrait",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "addEvent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvents",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "countEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Domain\\Event\\DomainEventInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 4,
        "effort": 144.76,
        "level": 0.25,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 9.05,
        "number_operators": 6,
        "number_operands": 8,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 30,
        "lloc": 25,
        "mi": 88.01,
        "mIwoC": 58.46,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.6,
        "relativeSystemComplexity": 2.6,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 13,
        "package": "App\\NF\\Domain\\Event\\EventLogs\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Event\\FailedSentNotificationEvent",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateCalled",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDetails",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface",
            "DateTimeImmutable",
            "ReflectionClass",
            "DateTimeImmutable",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 12,
        "volume": 111.13,
        "difficulty": 2.1,
        "effort": 233.38,
        "level": 0.48,
        "bugs": 0.04,
        "time": 13,
        "intelligentContent": 52.92,
        "number_operators": 10,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 39,
        "lloc": 39,
        "mi": 50.83,
        "mIwoC": 50.83,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 6.33,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 16.33,
        "totalSystemComplexity": 44.33,
        "package": "App\\NF\\Domain\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Event\\SentNotificationEvent",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateCalled",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDetailsNotification",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getType",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDetails",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface",
            "DateTimeImmutable",
            "ReflectionClass",
            "DateTimeImmutable",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Enum\\StatusEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\AggregateInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Domain\\Event\\NotificationDomainEventInterface"
        ],
        "lcom": 1,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 2.2,
        "effort": 260.27,
        "level": 0.45,
        "bugs": 0.04,
        "time": 14,
        "intelligentContent": 53.77,
        "number_operators": 11,
        "number_operands": 22,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 43,
        "lloc": 43,
        "mi": 49.72,
        "mIwoC": 49.72,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.63,
        "relativeSystemComplexity": 6.63,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 21,
        "totalSystemComplexity": 53,
        "package": "App\\NF\\Domain\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Model\\EmailDetailsNotification",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Domain\\Model\\DetailsNotification"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Domain\\Model\\DetailsNotification"
        ],
        "lcom": 1,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 75.11,
        "mIwoC": 75.11,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\NF\\Domain\\Model\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Model\\Notification",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "failedSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reSent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\NF\\Domain\\Model\\AggregateInterface",
            "App\\NF\\Domain\\Event\\EventLogs\\EventLogsWriteInterface",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Event\\CreatedNotificationEvent",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\TypeEnum",
            "App\\NF\\Domain\\Model\\DetailsNotification",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Event\\SentNotificationEvent",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Event\\FailedSentNotificationEvent",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Model\\NotificationId",
            "App\\NF\\Domain\\Enum\\StatusEnum"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Domain\\Model\\AggregateInterface",
            "App\\NF\\Domain\\Event\\EventLogs\\EventLogsWriteInterface"
        ],
        "lcom": 2,
        "length": 54,
        "vocabulary": 13,
        "volume": 199.82,
        "difficulty": 10,
        "effort": 1998.24,
        "level": 0.1,
        "bugs": 0.07,
        "time": 111,
        "intelligentContent": 19.98,
        "number_operators": 9,
        "number_operands": 45,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 10,
        "loc": 48,
        "lloc": 39,
        "mi": 81.4,
        "mIwoC": 48.91,
        "commentWeight": 32.48,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.96,
        "relativeSystemComplexity": 9.96,
        "totalStructuralComplexity": 63,
        "totalDataComplexity": 6.75,
        "totalSystemComplexity": 69.75,
        "package": "App\\NF\\Domain\\Model\\",
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 10,
        "instability": 0.77,
        "violations": {}
    },
    {
        "name": "App\\NF\\Domain\\Model\\NotificationId",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromUUID",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asUuid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "random",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Webmozart\\Assert\\Assert",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 21,
        "vocabulary": 8,
        "volume": 63,
        "difficulty": 4.2,
        "effort": 264.6,
        "level": 0.24,
        "bugs": 0.02,
        "time": 15,
        "intelligentContent": 15,
        "number_operators": 7,
        "number_operands": 14,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 1,
        "loc": 35,
        "lloc": 34,
        "mi": 66.67,
        "mIwoC": 53.72,
        "commentWeight": 12.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.38,
        "relativeSystemComplexity": 10.38,
        "totalStructuralComplexity": 54,
        "totalDataComplexity": 8.25,
        "totalSystemComplexity": 62.25,
        "package": "App\\NF\\Domain\\Model\\",
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 2,
        "instability": 0.29,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\DomainEvent\\DomainEventStore",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__clone",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__wakeup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInstance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addEvent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addArrayEvent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addManyEvent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvents",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "countEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 10,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Exception",
            "App\\NF\\Domain\\Event\\DomainEventInterface",
            "App\\NF\\Domain\\Event\\DomainEventInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 31,
        "vocabulary": 7,
        "volume": 87.03,
        "difficulty": 7.88,
        "effort": 685.35,
        "level": 0.13,
        "bugs": 0.03,
        "time": 38,
        "intelligentContent": 11.05,
        "number_operators": 10,
        "number_operands": 21,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 6,
        "loc": 61,
        "lloc": 55,
        "mi": 71.26,
        "mIwoC": 47.92,
        "commentWeight": 23.35,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.27,
        "relativeSystemComplexity": 4.27,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 47,
        "totalSystemComplexity": 47,
        "package": "App\\NF\\Infrastructure\\DomainEvent\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\DomainEvent\\DomainEventSubscribe",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postPersist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postRemove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "Doctrine\\ORM\\Event\\LifecycleEventArgs",
            "App\\NF\\Infrastructure\\DomainEvent\\DomainEventStore"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface"
        ],
        "lcom": 2,
        "length": 27,
        "vocabulary": 11,
        "volume": 93.4,
        "difficulty": 4.13,
        "effort": 385.29,
        "level": 0.24,
        "bugs": 0.03,
        "time": 21,
        "intelligentContent": 22.64,
        "number_operators": 5,
        "number_operands": 22,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 9,
        "loc": 41,
        "lloc": 32,
        "mi": 86.15,
        "mIwoC": 52.97,
        "commentWeight": 33.19,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 36.4,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 182,
        "package": "App\\NF\\Infrastructure\\DomainEvent\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Event\\CreateNotificationEvent",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Event\\RequestEvent",
            "App\\NF\\Infrastructure\\Factory\\CommandInterface",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        "implements": [
            "App\\NF\\Infrastructure\\Factory\\CommandInterface"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 78.06,
        "mIwoC": 78.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\NF\\Infrastructure\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Event\\EventDispatcher",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\NF\\Infrastructure\\Transports\\DomainEvent\\DomainEventBusInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 16,
        "lloc": 13,
        "mi": 98.96,
        "mIwoC": 67.88,
        "commentWeight": 31.08,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\NF\\Infrastructure\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Event\\EventStream",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "IncremetVersion",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateDate",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createEmptyStream",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEventNumber",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 1,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "DateTimeImmutable",
            "DateTimeImmutable",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Infrastructure\\Repository\\EventStoreRepositoryInterface",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "Symfony\\Component\\Uid\\Uuid"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 4.17,
        "effort": 492.93,
        "level": 0.24,
        "bugs": 0.04,
        "time": 27,
        "intelligentContent": 28.39,
        "number_operators": 8,
        "number_operands": 25,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 12,
        "loc": 50,
        "lloc": 39,
        "mi": 84.92,
        "mIwoC": 50.51,
        "commentWeight": 34.41,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.96,
        "relativeSystemComplexity": 5.96,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 15.67,
        "totalSystemComplexity": 47.67,
        "package": "App\\NF\\Infrastructure\\Event\\",
        "pageRank": 0.04,
        "afferentCoupling": 6,
        "efferentCoupling": 5,
        "instability": 0.45,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Event\\StoredEvent",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVersion",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Domain\\Event\\DomainEventInterface",
            "DateTimeImmutable",
            "App\\NF\\Domain\\Event\\DomainEventInterface"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 13,
        "volume": 59.21,
        "difficulty": 1.18,
        "effort": 69.97,
        "level": 0.85,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 50.1,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 25,
        "lloc": 17,
        "mi": 100.68,
        "mIwoC": 60.61,
        "commentWeight": 40.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.67,
        "relativeSystemComplexity": 3.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 11,
        "package": "App\\NF\\Infrastructure\\Event\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Exception\\InvalidParemeterRequest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0.63,
        "effort": 10.16,
        "level": 1.6,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 26.01,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.69,
        "mIwoC": 71.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\NF\\Infrastructure\\Exception\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\ExceptionEventSubscriber",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exception",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface",
            "Psr\\Log\\LoggerInterface",
            "Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface"
        ],
        "lcom": 3,
        "length": 29,
        "vocabulary": 14,
        "volume": 110.41,
        "difficulty": 3.14,
        "effort": 346.3,
        "level": 0.32,
        "bugs": 0.04,
        "time": 19,
        "intelligentContent": 35.2,
        "number_operators": 6,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 4,
        "loc": 26,
        "lloc": 22,
        "mi": 84.55,
        "mIwoC": 56.01,
        "commentWeight": 28.55,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 64.3,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 0.89,
        "totalSystemComplexity": 192.89,
        "package": "App\\NF\\Infrastructure\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Factory\\NotificationFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "request",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "command",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "response",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNameCommand",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Infrastructure\\Factory\\FactoryInterface",
            "App\\NF\\Infrastructure\\Factory\\RequestInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Exception",
            "App\\NF\\Infrastructure\\Factory\\CommandInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\NF\\Infrastructure\\Event\\CreateNotificationEvent",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "App\\NF\\Infrastructure\\Response\\NotificationResponse"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Infrastructure\\Factory\\FactoryInterface"
        ],
        "lcom": 4,
        "length": 7,
        "vocabulary": 3,
        "volume": 11.09,
        "difficulty": 1,
        "effort": 11.09,
        "level": 1,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 11.09,
        "number_operators": 3,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 64.17,
        "mIwoC": 64.17,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 14,
        "totalSystemComplexity": 14,
        "package": "App\\NF\\Infrastructure\\Factory\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Http\\SendNotificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "notification",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\EventDispatcher\\EventDispatcherInterface",
            "Psr\\Log\\LoggerInterface",
            "App\\NF\\Infrastructure\\Factory\\NotificationFactory",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 12,
        "vocabulary": 8,
        "volume": 36,
        "difficulty": 0.79,
        "effort": 28.29,
        "level": 1.27,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 45.82,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 2,
        "loc": 18,
        "lloc": 16,
        "mi": 87.39,
        "mIwoC": 62.7,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 33.2,
        "package": "App\\NF\\Infrastructure\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\PropertiesExtension",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "isAlwaysRead",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAlwaysWritten",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInitialized",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Laminas\\Code\\Reflection\\PropertyReflection",
            "Laminas\\Code\\Reflection\\PropertyReflection",
            "Laminas\\Code\\Reflection\\PropertyReflection"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 9,
        "vocabulary": 3,
        "volume": 14.26,
        "difficulty": 1.5,
        "effort": 21.4,
        "level": 0.67,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 9.51,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 65.52,
        "mIwoC": 65.52,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "App\\NF\\Infrastructure\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Repository\\DoctrineEventStoreRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "storeEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "countEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStream",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "aggregate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 8,
        "ccnMethodMax": 3,
        "externals": [
            "App\\NF\\Infrastructure\\Repository\\EventStoreRepositoryInterface",
            "App\\NF\\Infrastructure\\Repository\\EventStreamRepositoryInterface",
            "Symfony\\Component\\Uid\\Uuid",
            "Exception",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "App\\NF\\Domain\\Event\\DomainEventInterface",
            "App\\NF\\Infrastructure\\Event\\StoredEvent",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "Symfony\\Component\\Uid\\Uuid",
            "Symfony\\Component\\Uid\\Uuid"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Infrastructure\\Repository\\EventStoreRepositoryInterface"
        ],
        "lcom": 2,
        "length": 85,
        "vocabulary": 19,
        "volume": 361.07,
        "difficulty": 8.67,
        "effort": 3129.31,
        "level": 0.12,
        "bugs": 0.12,
        "time": 174,
        "intelligentContent": 41.66,
        "number_operators": 20,
        "number_operands": 65,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 16,
        "loc": 76,
        "lloc": 60,
        "mi": 74.85,
        "mIwoC": 42.23,
        "commentWeight": 32.62,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.48,
        "relativeSystemComplexity": 169.48,
        "totalStructuralComplexity": 1183,
        "totalDataComplexity": 3.36,
        "totalSystemComplexity": 1186.36,
        "package": "App\\NF\\Infrastructure\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Repository\\DoctrineEventStreamRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "App\\NF\\Infrastructure\\Repository\\EventStreamRepositoryInterface",
            "Doctrine\\Persistence\\ManagerRegistry",
            "Psr\\Log\\LoggerInterface",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "Symfony\\Component\\Uid\\Uuid",
            "App\\NF\\Infrastructure\\Event\\EventStream",
            "Symfony\\Component\\Uid\\Uuid",
            "Exception"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [
            "App\\NF\\Infrastructure\\Repository\\EventStreamRepositoryInterface"
        ],
        "lcom": 3,
        "length": 52,
        "vocabulary": 15,
        "volume": 203.16,
        "difficulty": 5.13,
        "effort": 1041.19,
        "level": 0.2,
        "bugs": 0.07,
        "time": 58,
        "intelligentContent": 39.64,
        "number_operators": 11,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 4,
        "loc": 41,
        "lloc": 37,
        "mi": 72.49,
        "mIwoC": 49.23,
        "commentWeight": 23.26,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 121.44,
        "totalStructuralComplexity": 484,
        "totalDataComplexity": 1.75,
        "totalSystemComplexity": 485.75,
        "package": "App\\NF\\Infrastructure\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Repository\\DoctrineNotificationRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "App\\NF\\Domain\\Repository\\NotificationRepositoryInterface",
            "Doctrine\\Persistence\\ManagerRegistry",
            "Psr\\Log\\LoggerInterface",
            "App\\NF\\Infrastructure\\Repository\\EventStoreRepositoryInterface",
            "App\\NF\\Domain\\Model\\Notification",
            "Symfony\\Component\\Uid\\Uuid"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [
            "App\\NF\\Domain\\Repository\\NotificationRepositoryInterface"
        ],
        "lcom": 2,
        "length": 17,
        "vocabulary": 8,
        "volume": 51,
        "difficulty": 1.14,
        "effort": 58.29,
        "level": 0.88,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 44.63,
        "number_operators": 1,
        "number_operands": 16,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 4,
        "loc": 19,
        "lloc": 15,
        "mi": 94.88,
        "mIwoC": 62.25,
        "commentWeight": 32.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 64.22,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.44,
        "totalSystemComplexity": 128.44,
        "package": "App\\NF\\Infrastructure\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Request\\NotificationRequest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "arrayHasKeys",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\NF\\Infrastructure\\Exception\\InvalidParemeterRequest",
            "Exception",
            "App\\NF\\Infrastructure\\Exception\\InvalidParemeterRequest"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 44,
        "vocabulary": 18,
        "volume": 183.48,
        "difficulty": 4.43,
        "effort": 812.54,
        "level": 0.23,
        "bugs": 0.06,
        "time": 45,
        "intelligentContent": 41.43,
        "number_operators": 13,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 7,
        "loc": 43,
        "lloc": 36,
        "mi": 78.65,
        "mIwoC": 49.39,
        "commentWeight": 29.26,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.93,
        "relativeSystemComplexity": 16.93,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.8,
        "totalSystemComplexity": 50.8,
        "package": "App\\NF\\Infrastructure\\Request\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Response\\NotificationResponse",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "App\\NF\\Infrastructure\\Factory\\ResponseInterface"
        ],
        "parents": [
            "Symfony\\Component\\HttpFoundation\\JsonResponse"
        ],
        "implements": [
            "App\\NF\\Infrastructure\\Factory\\ResponseInterface"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\NF\\Infrastructure\\Response\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Subscribe\\CreateNotificationSubscribe",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubscribedEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "crateNotification",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deserializeRequest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface",
            "Symfony\\Component\\Serializer\\SerializerInterface",
            "Symfony\\Component\\Messenger\\MessageBusInterface",
            "Psr\\Log\\LoggerInterface",
            "App\\NF\\Infrastructure\\Event\\CreateNotificationEvent",
            "App\\NF\\Infrastructure\\Request\\NotificationRequest",
            "Exception",
            "App\\NF\\Application\\Write\\Command\\CommandInterface",
            "App\\NF\\Application\\Write\\Command\\CommandInterface",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\EventDispatcher\\EventSubscriberInterface"
        ],
        "lcom": 3,
        "length": 55,
        "vocabulary": 27,
        "volume": 261.52,
        "difficulty": 4.66,
        "effort": 1218.44,
        "level": 0.21,
        "bugs": 0.09,
        "time": 68,
        "intelligentContent": 56.13,
        "number_operators": 14,
        "number_operands": 41,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 1,
        "loc": 33,
        "lloc": 32,
        "mi": 63.29,
        "mIwoC": 49.97,
        "commentWeight": 13.32,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 49.43,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 2.13,
        "totalSystemComplexity": 247.13,
        "package": "App\\NF\\Infrastructure\\Subscribe\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\NF\\Infrastructure\\Transports\\DomainEvent\\DomainEventBus",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\NF\\Infrastructure\\Transports\\DomainEvent\\DomainEventBusInterface",
            "Symfony\\Component\\Messenger\\MessageBusInterface",
            "App\\NF\\Domain\\Event\\DomainEventInterface"
        ],
        "parents": [],
        "implements": [
            "App\\NF\\Infrastructure\\Transports\\DomainEvent\\DomainEventBusInterface"
        ],
        "lcom": 2,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0,
        "effort": 0,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 71.53,
        "mIwoC": 71.53,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\NF\\Infrastructure\\Transports\\DomainEvent\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]