#!/bin/bash
echo ":: Run Other Test"
docker-compose exec php ./bin/phpunit --testdox --exclude-group Unit,unit,U,u --exclude-group Integration,integration,I,i --exclude-group Application,application,A,a