#!/bin/bash

  # DIR=./var
  # if [ -d "$DIR" ]
  # then
  #   echo "Remove Var"
  #   chmod -R 777 ./var
  #   rm -rf "$DIR"
  # fi
  # mkdir ./var
  # chmod -R 777 ./var

docker-compose exec -T php "$@"